### PR TITLE
resolves #43 to improve the performance when pulling large amount of bin...

### LINKED ISSUE #43: Git fat pull has poor performance when dealing with large amount of binaries
Hi, this issue is related with #37, while has a different scenario.

I find that when dealing with a repository which contains large amount of binaries, the performance of 
`git fat pull` becomes really bad.

We are migrating from clearcase to git these days and the git repository comes from a real cleacase vob, which is 600M and has 3420 binaries. I tested on a Ubuntu 14.04 machine with gigabytes network.

The test result of `time git fat pull` shows:

```bash
real 33m41.071s
user 21m6.557s
sys 11m13.053s
```

This is even slower than clearcase ~

Than I used cProfile and pstats to analysis the performance data, which shows the `checkout()` method is the hot spot, specifically these lines:

```python
for digest, fname in self._orphan_files():
    sub.check_call(['git', 'checkout-index', '--index', '--force', fname])
```

Per my understanding, the `checkout-index` command does three things here:

1. find the specific file in the index
2. trigger the smudge filter
3. copy the actual content of binary file

Further test shows the first step takes most of the time, I think since the index is very large and contains a lot of files, git needs some time to find out a specific file from the index. When we have lots of orphan files, the `checkout-index` command need to be executed lots of times, which makes
the performance  really bad.

I come up with a rough solution —— move the `checkout-index` line out of loop and checkout all the files from the index instead:

```python
 sub.check_call(['git', 'checkout-index', '--index', '--force', '--all'])
```
After this change, the performance improves a lot:

```bash
real 12m43.525s
user 8m12.750s
sys 4m22.912s
 ```

Will send a pull request and explain details later.
Any comments and suggestions of this issue are more than welcome.

### PR DESCRIPTION
**Pull request by demonyangyue**
Instead of checking out orphan files from index one by one, checkout all the files from index to avoid file searching overhead, which makes checkout 3 times  faster.

Some concerns you may have:

1. Is this solution functionally right?
The only risk here is overwriting those unstaged changes. So I add some check and remind user if there exists unstaged changes.

2. If `git fat pull` only needs to deal with several binaries(most files in the repository are plain text), how about the performance now?
Per my test , though we checkout all files from index , git is smart enough to tell whether updating content or not. The performance remains good if there are only several binaries to deal with.

Thanks

### CODE REVIEW

**Comment by abraithwaite** [comment]
Ah, I see you do handle it.  I'll review this more closely in the morning.  I'm not sure it's okay to exit in the middle of that function. If it is okay though, it looks good!

**Comment by demonyangyue** [comment]
A new command switch "--plenty-binaries" is provided to avoid interfering with the old behavior.

**Comment by justinclift** [comment]
Two thoughts:

* "plenty-binaries" is a really, really non-english style of phrase (it would never be said by a native english speaker).  Maybe "many-binaries" instead? :smile:
* Would you be ok to squash both of these commits into a single one for this pull request?  It makes the history for the repository easier to work with for future people.

**Comment by demonyangyue** [comment]
@justinclift, really appreciated for your suggestions, I have revised the commits.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by abraithwaite** [comment]
Awesome thanks!  I think the argument is a good decision.  The default behavior makes it so that you can switch branches without having to stash changes, but for performance (e.g. initial clones), this will work better.

**Pull request merged**
