### PR TITLE
Add support for rsyncd shares to the rsync backend

### PR DESCRIPTION
**Pull request by ajohnson23**
Currently, this only supports passwordless rsyncd shares, since this is what I use here. I can add user / pass
parameters if there is demand for it.

rsyncd man here -
https://www.samba.org/ftp/rsync/rsyncd.conf.html

### CODE REVIEW

**Comment by justinclift** [comment]
Any interest in merging these into a single commit (instead of 3)?  That way, it makes for a cleaner commit history if/when it gets merged. :smile:

**Comment by ajohnson23** [comment]
Sure, done!

**Comment by abraithwaite** [comment]
This is great, thanks!  It's also another reminder that documentation needs to be cleaned up, but I won't pin that on you. (Unless you want to of course!)
:beers:

**Comment by justinclift** [comment]
@ajohnson23 Awesome. :grinning:

**Pull request merged**
