### PR TITLE
Some rsync improvements

### PR DESCRIPTION
**Pull request by lpsinger**
This pull request includes two enhancements:
- Support partial pulls with the following syntax:
  
  ```
  $ git fat pull foo.png bar.png bat.png
  $ git fat pull rsync foo.png bar.png bat.png
  ```
- If the [`GIT_SSH`](http://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#Miscellaneous) environment variable is set, use its value as the rsync shell.

### CODE REVIEW

**Comment by justinclift** [comment]
Would you be ok to squash both of those commits into just one?  It makes things easier for future git operations when Pull Requests are one commit big. :smile:

**Comment by lpsinger** [comment]
OK. Mind if I do a `push -f`?

**Comment by lpsinger** [comment]
Was I correct to open the pull request against `master`, or should I have used `develop`?

**Comment by abraithwaite** [comment]
Oh yes, please open it against develop.  Master is stable.  By all means, you can do force push to your own branch. :+1:

Patterns aren't something I've thought too much about yet, but what you've presented is pretty much what I had in mind.  I'm not sure if there would be a better way to handle it though.  At least we abstract it away from the backend.

Finally, can you also rename `pattern` to `patterns` so it's clear we're passing in a list instead of a single pattern?  I just verified that `git ls-files` can handle multiple arguments so this should be fine.

Thanks!

**Comment by lpsinger** [comment]
Squashed into #46.

**Pull request closed without merging**
