### PR TITLE
Support partial pulls and respect GIT_SSH

### PR DESCRIPTION
**Pull request by lpsinger**
First, allow pulling individual files with the following syntax:

```
$ git fat pull foo.png bar.png bat.png
$ git fat pull rsync foo.png bar.png bat.png
```

Second, use GIT_SSH for rsync transport. If the user has configured git to
use a particular ssh command by setting the environment variable `GIT_SSH`,
then use that command as the rsync shell.

See also git's documentation on this environment variable:
http://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#Miscellaneous

This is a squash of #45, with some comments addressed.

### CODE REVIEW

**Comment by abraithwaite** [comment]
Looks great! :+1:
Thanks! :smiley:

**Comment by lpsinger** [comment]
Thank you! By the way, when is your next release?

**Comment by abraithwaite** [comment]
Well I guess I'm going to have to now that I've merged so much in the past week now won't I?

I think I'm going to do one this weekend.  :-)

**Comment by CzarekTomczak** [comment]
OT: @abraithwaite It would be a good idea to fix this while doing a release, as currently git-fat on Mac seems to be broken and not usable: https://github.com/cyaninc/git-fat/pull/35#issuecomment-74101342

**Comment by abraithwaite** [comment]
I didn't get around to it this weekend.  Sorry about that.  I want to go through and sanity check some things before doing a release which I didn't have time for.  It's also going to take a bit longer if we want to roll in the rsync change for OSX.

**Comment by lpsinger** [comment]
Any chance of a release soon? I am using git-fat now for a paper that I am working on and I would love to tell my collaborators that they can `pip install` it instead of installing from my branch. Sorry for being pushy!

**Comment by abraithwaite** [comment]
Thanks for reminding me.  I wanted to address the OSX rsync issue first (can't find it right now) but I said I would do it two weeks ago so I decided it's time.  Sorry for the delay. :bus:

**Comment by lpsinger** [comment]
Thank you! BTW, nice work with git-fat.

**Pull request merged**
